<a href="https://colab.research.google.com/github/Diego-1099/Colabfiles/blob/main/Practica_4__Manipulaci%C3%B3n_de_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Manipulación de matrices**

In [4]:
import numpy as np

matriz1 = np.random.randint(1,11,(3,3))
matriz2 = np.random.randint(1,11,(3,3))

suma = matriz1 + matriz2
resta = matriz1 - matriz2
multiplicacion = matriz1 * 2
multiplicacion_matrices = np.dot(matriz1, matriz2)

print('-------------------------------')
print('Matriz 1 :\n',matriz1)
print('-------------------------------')
print('Matriz 2 :\n', matriz2)
print('-------------------------------')
print('Suma :\n', suma)
print('-------------------------------')
print('Resta :\n', resta)
print('-------------------------------')
print('Multiplicacion :\n', multiplicacion)
print('-------------------------------')
print('Multiplicacion de matrices :\n', multiplicacion_matrices)


-------------------------------
Matriz 1 :
 [[9 8 2]
 [5 9 5]
 [8 7 6]]
-------------------------------
Matriz 2 :
 [[ 5  5 10]
 [ 9  9  3]
 [ 5  9  2]]
-------------------------------
Suma :
 [[14 13 12]
 [14 18  8]
 [13 16  8]]
-------------------------------
Resta :
 [[ 4  3 -8]
 [-4  0  2]
 [ 3 -2  4]]
-------------------------------
Multiplicacion :
 [[18 16  4]
 [10 18 10]
 [16 14 12]]
-------------------------------
Multiplicacion de matrices :
 [[127 135 118]
 [131 151  87]
 [133 157 113]]
